class ValueHolder {
  static String? loginUserId;
  static String? userIdToVerify;
  static String? userPhoto;
  static String? userPhone;
  static String? userNameToVerify;
  static String? userEmailToVerify;
  static String? userPhoneToVerify;
  static String? userPasswordToVerify;
  static String? deviceToken;
  static bool? notiSetting;
  static bool? loginBySocialMedia;
  static String overAllTaxLabel = "0";
  static String overAllTaxValue = "0";
  static String shippingTaxLabel = "0";
  static String? shopId="";
  static String? shopName;
  static String? messenger;
  static String? whatsApp;
  static String? phone;

  static String? appInfoVersionNo;
  static bool? appInfoForceUpdate;
  static String? appInfoForceUpdateTitle;
  static String? appInfoForceUpdateMsg;
  static String? startDate;
  static String? endDate;
  static String? paypalEnabled;
  static String? stripeEnabled;
  static String? codEnabled;
  static String? bankEnabled;
  static String? publishKey;
  static String? shippingId;
  static String? standardShippingEnable;
  static String? zoneShippingEnable;
  static String? noShippingEnable;
  static String? shippingFirstName;
  static String? shippingLastName;
  static String? shippingEmail;
  static String? shippingTaxValue;
  static String? shippingCostValue;
  static String? shippingPhone;
  static String? shippingAddress;
  static String? shippingAddress2;
  static String? shippingCity;

  static String? shippingCityId;
  static String? shippingCountry;
  static String? shippingCountryId;

  static String? shippingState;
  static String? shippingPostalCode;
  static String? shippingCompany;
  static double? lat;
  static double? lng;
  static String? address;
  static String? billingFirstName;
  static String? billingLastName;
  static String? billingCompany;
  static String? billingAddress;
  static String? billingAddress1;
  static String? billingCountry;
  static String? billingCountryId;
  static String? billingState;
  static String? billingCity;
  static String? billingCityId;
  static String? billingPostalCode;
  static String? billingEmail;
  static String? billingPhone;
}
